pretrained_model_path: "./ckpt/stable-diffusion-v1-5"
logdir: "./runs"
train_dataset:
    path: "./data/surfing"
    prompt: "a man is surfing a wave"
    n_sample_frame: 8
    sampling_rate: 1
    stride: 1
validation_sample_logger:
    prompts: [
        "a man is surfing a wave",
        "a sloth is surfing a wave",
        "an astronaut is surfing on mars",
        "a man is surfing a wave cartoon style",
    ]
    clip_length: "${..train_dataset.n_sample_frame}"
    num_samples_per_prompt: 1
    num_inference_steps: 20
    guidance_scale: 7
train_steps: 1000
validation_steps: 100
checkpointing_steps: 1000
seed: 0
learning_rate: 1e-5
prior_preservation: 0.5
train_temporal_conv: False
